<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AgentBlazor" Version="0.2.1" />
    <PackageReference Include="MudBlazor" Version="9.0.0" />
  </ItemGroup>
</Project>
