using System.Text;
using System.Text.RegularExpressions;
using AgentBlazor.Cli.Analysis.Models;

namespace AgentBlazor.Cli.Analysis.Generation;

/// <summary>
/// Generates a single AGENT.md file summarizing the Blazor application.
/// This is the only output file - agents can read source code directly for details.
/// Preserves developer-edited sections on regeneration.
/// </summary>
public sealed partial class MarkdownGenerator
{
    // Methods that aren't useful as agent actions
    private static readonly string[] ExcludePatterns =
    [
        "Visible", "Dialog", "SetActive", "SetCurrent", "SetSelected", "SetExpanded",
        "LoadAsync", "GetRoute", "GetJourney", "GetNext", "GetTools", "GetSnapshot",
        "GetSuggestions", "GetStatistics", "GetTrace", "GetInsight"
    ];

    // Services that are implementation details, not useful for agents
    private static readonly string[] ExcludeServices =
    [
        "Null", "InMemory", "Static", "PatternBased", "JsonFile", "Mock", "Fake", "Stub", "Test"
    ];

    // Service name suffixes that indicate infrastructure/data access (lower priority for agents)
    private static readonly string[] InfrastructureServiceSuffixes =
    [
        "Store", "Repository", "DataAccess", "DbContext", "Cache", "Logger", "Factory"
    ];

    // Sections that are auto-generated (will be replaced on update)
    private static readonly HashSet<string> AutoGeneratedSections =
    [
        "Routes",
        "Actions",
        "Services"
    ];

    // Sections that are developer-editable (will be preserved on update)
    private static readonly HashSet<string> DeveloperSections =
    [
        "Agent Instructions",
        "Priority Workflows"
    ];

    // Default placeholder content (if section contains only this, treat as empty)
    private const string AgentInstructionsPlaceholder = "<!-- Add guidelines for agents";
    private const string PriorityWorkflowsPlaceholder = "<!-- Document key business flows";

    /// <summary>
    /// Generates the AGENT.md file from the project model.
    /// Preserves developer-edited sections if the file already exists.
    /// </summary>
    public async Task GenerateAsync(
        ProjectModel model,
        string outputDirectory,
        CancellationToken ct = default)
    {
        var agentBlazorDir = Path.Combine(outputDirectory, ".agentblazor");
        Directory.CreateDirectory(agentBlazorDir);

        var agentMdPath = Path.Combine(agentBlazorDir, "AGENT.md");

        // Read existing content to preserve developer sections
        Dictionary<string, string> preservedSections = [];
        if (File.Exists(agentMdPath))
        {
            var existingContent = await File.ReadAllTextAsync(agentMdPath, ct).ConfigureAwait(false);
            preservedSections = ParseSections(existingContent);
        }

        var content = GenerateAgentMarkdown(model, outputDirectory, preservedSections);
        await File.WriteAllTextAsync(agentMdPath, content, ct).ConfigureAwait(false);
    }

    /// <summary>
    /// Parses markdown content into sections by ## headings.
    /// </summary>
    private static Dictionary<string, string> ParseSections(string markdown)
    {
        var sections = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

        // Match ## Section Name and capture content until next ## or end
        var matches = SectionRegex().Matches(markdown);

        for (var i = 0; i < matches.Count; i++)
        {
            var sectionName = matches[i].Groups[1].Value.Trim();
            var startIndex = matches[i].Index + matches[i].Length;
            var endIndex = i + 1 < matches.Count ? matches[i + 1].Index : markdown.Length;

            // Also stop at --- (footer separator) - handle both Unix and Windows line endings
            var footerMatch = FooterRegex().Match(markdown, startIndex);
            if (footerMatch.Success && footerMatch.Index < endIndex)
                endIndex = footerMatch.Index;

            var content = markdown[startIndex..endIndex].Trim();
            sections[sectionName] = content;
        }

        return sections;
    }

    /// <summary>
    /// Checks if a section contains only placeholder content (not edited by developer).
    /// </summary>
    private static bool IsPlaceholderOnly(string sectionName, string content)
    {
        if (string.IsNullOrWhiteSpace(content))
            return true;

        // Check for known placeholders
        return sectionName switch
        {
            "Agent Instructions" => content.Contains(AgentInstructionsPlaceholder),
            "Priority Workflows" => content.Contains(PriorityWorkflowsPlaceholder),
            _ => false
        };
    }

    [GeneratedRegex(@"^## (.+)$", RegexOptions.Multiline)]
    private static partial Regex SectionRegex();

    [GeneratedRegex(@"\r?\n---\r?\n")]
    private static partial Regex FooterRegex();

    private string GenerateAgentMarkdown(
        ProjectModel model,
        string baseDir,
        Dictionary<string, string> preservedSections)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine($"# {model.AppName}");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(model.Description))
        {
            sb.AppendLine(model.Description);
            sb.AppendLine();
        }

        // Coverage badge
        if (model.Coverage != null)
        {
            var coverage = model.Coverage;
            sb.AppendLine($"**Coverage:** {coverage.ConfirmedActions}/{coverage.TotalActions} actions confirmed ({coverage.ActionCoveragePercent}%)");
            sb.AppendLine();
        }

        sb.AppendLine("> Auto-generated by `agentblazor`. Read source files directly for details.");
        sb.AppendLine();

        // Routes
        sb.AppendLine("## Routes");
        sb.AppendLine();
        sb.AppendLine("| Route | Component | File |");
        sb.AppendLine("|-------|-----------|------|");
        foreach (var route in model.Routes.OrderBy(r => r.Template))
        {
            sb.AppendLine($"| `{route.Template}` | {route.ComponentName} | `{route.ComponentFile}` |");
        }
        sb.AppendLine();

        // Actions
        sb.AppendLine("## Actions");
        sb.AppendLine();

        var confirmedActions = model.Actions
            .Where(a => a.ExposureMode == ActionExposureMode.Confirmed)
            .OrderBy(a => a.SourceService)
            .ThenBy(a => a.Name)
            .ToList();

        var confirmedNames = confirmedActions.Select(a => a.Name).ToHashSet();

        // Filter discovered: higher threshold, exclude UI state, exclude duplicates of confirmed
        // Also exclude infrastructure services (stores, repositories, etc.)
        var suggestedActions = model.Actions
            .Where(a => a.ExposureMode == ActionExposureMode.Suggested && a.Score >= 0.7)
            .Where(a => !IsExcludedMethod(a.MethodName))
            .Where(a => !IsExcludedService(a.SourceService))
            .Where(a => !IsInfrastructureService(a.SourceService))
            .Where(a => !confirmedNames.Contains(a.Name)) // No duplicates
            .OrderByDescending(a => a.Score)
            .ThenBy(a => a.SourceService)
            .ToList();

        if (confirmedActions.Count > 0)
        {
            sb.AppendLine("### Confirmed");
            sb.AppendLine();
            foreach (var action in confirmedActions)
            {
                WriteActionLine(sb, action, baseDir);
            }
            sb.AppendLine();
        }

        if (suggestedActions.Count > 0)
        {
            sb.AppendLine("### Discovered");
            sb.AppendLine();
            foreach (var action in suggestedActions)
            {
                WriteActionLine(sb, action, baseDir);
            }
            sb.AppendLine();
        }

        // Services - compact list, exclude mock/null implementations
        sb.AppendLine("## Services");
        sb.AppendLine();
        foreach (var service in model.Services
            .Where(s => !IsExcludedService(s.TypeName))
            .OrderBy(s => s.TypeName))
        {
            var relativePath = MakeRelativePath(baseDir, service.FilePath);
            sb.AppendLine($"- `{service.TypeName}` — {relativePath}");
        }
        sb.AppendLine();

        // Agent Instructions - preserve developer content or show placeholder
        sb.AppendLine("## Agent Instructions");
        sb.AppendLine();
        if (preservedSections.TryGetValue("Agent Instructions", out var agentInstructions) &&
            !IsPlaceholderOnly("Agent Instructions", agentInstructions))
        {
            sb.AppendLine(agentInstructions);
        }
        else
        {
            sb.AppendLine("<!-- Add guidelines for agents working with this codebase:");
            sb.AppendLine("- \"Always confirm before executing mutation actions\"");
            sb.AppendLine("- \"Check workflow state before advancing stages\"");
            sb.AppendLine("- \"Prefer recovery playbooks over manual resets\"");
            sb.AppendLine("-->");
        }
        sb.AppendLine();

        // Priority Workflows - preserve developer content or show placeholder
        sb.AppendLine("## Priority Workflows");
        sb.AppendLine();
        if (preservedSections.TryGetValue("Priority Workflows", out var priorityWorkflows) &&
            !IsPlaceholderOnly("Priority Workflows", priorityWorkflows))
        {
            sb.AppendLine(priorityWorkflows);
        }
        else
        {
            sb.AppendLine("<!-- Document key business flows agents should understand:");
            sb.AppendLine("1. **Incident Escalation**: Triage → Evidence Review → Escalation Brief → Handoff");
            sb.AppendLine("2. **Release Process**: Readiness Check → Draft Preparation → Approval");
            sb.AppendLine("-->");
        }
        sb.AppendLine();

        // Preserve any custom sections the developer added
        foreach (var (sectionName, content) in preservedSections)
        {
            // Skip auto-generated and known developer sections (already handled)
            if (AutoGeneratedSections.Contains(sectionName) ||
                DeveloperSections.Contains(sectionName) ||
                sectionName.Equals("Recommendations", StringComparison.OrdinalIgnoreCase))
                continue;

            // This is a custom section - preserve it
            sb.AppendLine($"## {sectionName}");
            sb.AppendLine();
            sb.AppendLine(content);
            sb.AppendLine();
        }

        // Recommendations section (auto-generated, not preserved)
        if (model.Recommendations.Count > 0)
        {
            sb.AppendLine("## Recommendations");
            sb.AppendLine();
            sb.AppendLine("To improve agent comprehension, consider adding these attributes:");
            sb.AppendLine();

            foreach (var rec in model.Recommendations.Take(10))
            {
                var icon = rec.Type switch
                {
                    RecommendationType.AddAgentAction => "→",
                    RecommendationType.AddAgentCapability => "★",
                    RecommendationType.AddDescription => "✎",
                    RecommendationType.AddApprovalTag => "⚠",
                    _ => "•"
                };

                sb.AppendLine($"- {icon} **{rec.TargetName}**");
                sb.AppendLine($"  - {rec.Suggestion}");
                if (!string.IsNullOrEmpty(rec.FilePath))
                {
                    var relativePath = MakeRelativePath(baseDir, rec.FilePath);
                    sb.AppendLine($"  - Location: {relativePath}");
                }
            }
            sb.AppendLine();
        }

        // Footer
        sb.AppendLine("---");
        sb.AppendLine($"*Generated: {model.GeneratedAtUtc:yyyy-MM-dd HH:mm:ss} UTC*");

        return sb.ToString();
    }

    private static void WriteActionLine(StringBuilder sb, ActionModel action, string baseDir)
    {
        var tags = new List<string>();
        if (action.IsMutationLikely) tags.Add("mutation");
        if (action.RequiresApproval) tags.Add("approval");

        var tagStr = tags.Count > 0 ? $" `[{string.Join(", ", tags)}]`" : "";

        // Method signature with parameters
        var methodName = action.MethodName;
        if (methodName.EndsWith("Async"))
            methodName = methodName[..^5];

        var paramStr = FormatParameters(action.Parameters);
        var signature = $"`{methodName}({paramStr})`";

        // File path
        var relativePath = MakeRelativePath(baseDir, action.FilePath);

        sb.AppendLine($"- **{action.Name}**{tagStr}");
        sb.AppendLine($"  - {signature} — {relativePath}");

        // Routes if any
        if (action.RelevantRoutes.Count > 0)
        {
            sb.AppendLine($"  - Routes: {string.Join(", ", action.RelevantRoutes.Select(r => $"`{r}`"))}");
        }

        // Description if meaningful
        if (!IsTrivialDescription(action.Summary))
        {
            sb.AppendLine($"  - {action.Summary}");
        }
    }

    private static string FormatParameters(IReadOnlyList<ParameterModel> parameters)
    {
        // Filter out context-bound parameters (auto-injected by runtime)
        var userParams = parameters.Where(p => !p.IsContextBound).ToList();

        if (userParams.Count == 0)
            return "";

        return string.Join(", ", userParams.Select(p =>
        {
            var typeName = SimplifyTypeName(p.TypeName);
            var optional = p.IsOptional ? "?" : "";
            var required = p.IsRequired ? "!" : "";
            var allowed = !string.IsNullOrEmpty(p.AllowedValues) ? $" [{p.AllowedValues}]" : "";
            return $"{p.Name}: {typeName}{optional}{required}{allowed}";
        }));
    }

    private static string SimplifyTypeName(string typeName)
    {
        // Simplify common types for readability
        return typeName
            .Replace("System.", "")
            .Replace("Collections.Generic.", "")
            .Replace("Threading.Tasks.", "")
            .Replace("Int32", "int")
            .Replace("Int64", "long")
            .Replace("String", "string")
            .Replace("Boolean", "bool")
            .Replace("Double", "double")
            .Replace("Single", "float");
    }

    private static bool IsExcludedMethod(string methodName)
    {
        return ExcludePatterns.Any(p => methodName.Contains(p, StringComparison.OrdinalIgnoreCase));
    }

    private static bool IsExcludedService(string serviceName)
    {
        return ExcludeServices.Any(p => serviceName.StartsWith(p, StringComparison.OrdinalIgnoreCase));
    }

    private static bool IsInfrastructureService(string serviceName)
    {
        return InfrastructureServiceSuffixes.Any(p => serviceName.EndsWith(p, StringComparison.OrdinalIgnoreCase));
    }

    private static bool IsTrivialDescription(string? desc)
    {
        if (string.IsNullOrEmpty(desc)) return true;
        if (desc.StartsWith("Action from")) return true;
        // Auto-generated descriptions are just "Method name." with spaces
        var words = desc.TrimEnd('.').Split(' ');
        return words.Length <= 3 && char.IsUpper(desc[0]);
    }

    private static string MakeRelativePath(string basePath, string fullPath)
    {
        if (string.IsNullOrEmpty(fullPath)) return "";

        try
        {
            // If already relative, return as-is
            if (!Path.IsPathRooted(fullPath))
                return fullPath;

            var baseUri = new Uri(basePath.TrimEnd(Path.DirectorySeparatorChar) + Path.DirectorySeparatorChar);
            var fullUri = new Uri(fullPath);
            var relativeUri = baseUri.MakeRelativeUri(fullUri);
            return Uri.UnescapeDataString(relativeUri.ToString().Replace('/', Path.DirectorySeparatorChar));
        }
        catch
        {
            return fullPath;
        }
    }
}
