namespace AgentBlazor.Core.Paid.Suggestions;

/// <summary>
/// Context for generating smart suggestions.
/// </summary>
public record SuggestionContext(
    string SessionId,
    string? UserId,
    string? CurrentRoute,
    IReadOnlyList<string> RecentActions,
    IReadOnlyDictionary<string, object?>? PageState = null);

/// <summary>
/// A smart suggestion with source tracking.
/// </summary>
public record SmartSuggestion(
    string Text,
    string ActionId,
    float Confidence,
    SuggestionSource Source);

/// <summary>
/// Source of the suggestion.
/// </summary>
public enum SuggestionSource
{
    /// <summary>
    /// Derived from historical action sequences (A→B→C patterns).
    /// </summary>
    Pattern,

    /// <summary>
    /// Most popular action for the current route.
    /// </summary>
    Popular,

    /// <summary>
    /// Generated by LLM when pattern confidence is low.
    /// </summary>
    Llm
}

/// <summary>
/// An action sequence pattern (A followed by B often leads to C).
/// </summary>
public record ActionSequencePattern(
    IReadOnlyList<string> PrecedingActions,
    string NextAction,
    int Occurrences,
    float Confidence);
